name: tsg
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - cudatoolkit=11.7
  - pytorch=2.0.0
  - torchaudio=2.0.0
  - nvidia-cudnn-cu11=8.5.0.96
  - nvidia-cublas-cu11=11.10.3.66
  - numpy=1.23.5
  - scipy=1.10.1
  - pandas=2.0.2
  - scikit-learn=1.2.2
  - seaborn=0.12.2
  - matplotlib=3.7.2
  - progressbar2=3.55.0
  - speechbrain
